package com.sentinel.alert;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Table(name = "alerts")
@Getter
@Setter
@NoArgsConstructor
public class AlertEntity {

    @Id
    @Column(name = "id")
    private String id;

    @Column(name = "site_id", nullable = false)
    private String siteId;

    @Column(name = "severity", nullable = false)
    private String severity;

    @Column(name = "status", nullable = false)
    private String status;

    @Column(name = "title", nullable = false)
    private String title;

    @Column(name = "description")
    private String description;

    @Column(name = "rule")
    private String rule;

    @Column(name = "record_ids", columnDefinition = "TEXT")
    private String recordIds;

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt;

    @Column(name = "acknowledged_at")
    private LocalDateTime acknowledgedAt;

    @Column(name = "acknowledged_by")
    private String acknowledgedBy;

    /**
     * Rich, human-readable narrative generated by NarrativeService at alert-creation time.
     * Surfaces directly in the dashboard feed as the primary text a safety officer reads.
     * Stored as TEXT so multi-sentence narratives are fully supported.
     */
    @Column(name = "narrative", columnDefinition = "TEXT")
    private String narrative;

    /**
     * Timestamp of when the narrative was last written or refreshed.
     * Set at creation and updated whenever the staleness check rewrites the narrative.
     * Allows the UI to show "updated 2h ago" vs "generated 3 days ago".
     */
    @Column(name = "narrative_updated_at")
    private LocalDateTime narrativeUpdatedAt;

    /**
     * The incident count for this site that was used to generate the current narrative.
     * Stored explicitly so the staleness check can compare reliably — avoids
     * regex-parsing the narrative text, which breaks when the LLM rewrites phrasing.
     */
    @Column(name = "narrative_incident_count")
    private Long narrativeIncidentCount = 0L;

    @Column(name = "required_qualification")
    private String requiredQualification;
}
