/** Severity bands — matches Stage 1 validate.py vocabulary exactly */
export type SeverityBand = "Low" | "Medium" | "High" | "Critical";

/** Decision outcomes from Stage 1 decide.py */
export type DecisionOutcome = "trusted" | "corrected" | "review" | "rejected";

/** Alert status */
export type AlertStatus = "active" | "acknowledged" | "resolved";

// Risk Summary

export interface SiteRiskSummary {
  siteId: string;
  siteName: string;
  latitude: number;
  longitude: number;
  riskScore: number;
  severityBand: SeverityBand;
  incidentCount: number;
  pressureSpikeCount: number;
  lastAuditDate: string;
  daysSinceLastAudit: number;
  correctedRate: number;
  rejectedRate: number;
  /** ML model: probability of a Critical incident in the next 7 days (0.0–1.0). Null if model not trained. */
  incidentProbability7d?: number | null;
  /** Risk band derived from model probability: HIGH / MODERATE / LOW / UNKNOWN */
  modelRiskBand?: string | null;
}

// Alerts

export interface Alert {
  id: string;
  siteId: string;
  siteName: string;
  severity: SeverityBand;
  status: AlertStatus;
  title: string;
  description: string;
  rule: string;
  recordIds: string[];
  createdAt: string;
  acknowledgedAt?: string;
  acknowledgedBy?: string;
  /**
   * Rich, human-readable narrative generated by NarrativeService at alert-creation time.
   * Contains contextual details — cohort activity, disbursement gaps, field visit recency, and beneficiary risk signals.
   * May be undefined for alerts created before V11 migration.
   */
  narrative?: string;
  /**
   * ISO timestamp of when the narrative was last written or refreshed.
   * Undefined for pre-V12 alerts (backfilled with createdAt on migration).
   */
  narrativeUpdatedAt?: string;
}

// Data Quality

export interface DataQualitySummary {
  trusted: number;
  corrected: number;
  review: number;
  rejected: number;
  total: number;
  passRate: number;
  gateStatus: "passed" | "failed";
  threshold: number;
  lastBatchId: string;
  lastBatchDate: string;
}

export interface IngestBatch {
  batchId: string;
  sourceFilename: string;
  rowCount: number;
  sha256Checksum: string;
  ingestedAt: string;
  trustedCount: number;
  correctedCount: number;
  reviewCount: number;
  rejectedCount: number;
}

// Telemetry

export interface TelemetryReading {
  readingId: string;
  timestamp: string;
  site: string;
  pipelineSection: string;
  pressurePsi: number | null;
  flowRateBph: number | null;
  temperatureCelsius: number | null;
  valveStatus: string;
  sensorId: string;
}

export interface TelemetrySummary {
  totalReadings: number;
  pressureSpikeCount: number;
  sensorDropoutCount: number;
  avgPressure: number;
  avgFlowRate: number;
  avgTemperature: number;
}

// Site Detail

export interface Incident {
  incidentId: string;
  siteId: string;
  latitude?: number;
  longitude?: number;
  incidentDate: string;
  severity: SeverityBand;
  description: string;
  complianceScore: number;
  decision: DecisionOutcome;
  decisionReason: string;
  closedDate?: string;
}

export interface Audit {
  auditId: string;
  siteId: string;
  inspectionDate: string;
  auditor: string;
  findings: string;
  complianceScore: number;
  followUpRequired: boolean;
}

export interface SiteDetail {
  siteId: string;
  siteName: string;
  location: string;
  latitude: number;
  longitude: number;
  riskScore: number;
  severityBand: SeverityBand;
  pressureSpikeCount: number;
  // Risk formula inputs — used by breakdown panel and what-if slider
  incidentCount: number;
  critHighCount: number;
  daysSinceAudit: number;
  rejectedRate: number;
  incidents: Incident[];
  audits: Audit[];
  telemetryReadings: TelemetryReading[];
  /** Active alerts for this site — used to show the narrative briefing at the top of the detail page. */
  activeAlerts?: Alert[];
}

// What-If Simulation

export interface WhatIfRequest {
  incidentCountOverride?: number;
  critHighPercentOverride?: number;  // 0-100 percentage
  daysSinceAuditOverride?: number;
  rejectionRateOverride?: number;    // 0.0-1.0 fraction
  pressureSpikesOverride?: number;
}

export interface WhatIfResponse {
  currentScore: number;
  currentBand: SeverityBand;
  simulatedScore: number;
  simulatedBand: SeverityBand;
  scoreDelta: number;
  incidentFrequencyContrib: number;  // max 30.0
  severityMixContrib: number;        // max 30.0
  auditRecencyContrib: number;       // max 20.0
  rejectionRateContrib: number;      // max 10.0
  pressureSpikesContrib: number;     // max 10.0
  liveDaysSinceAudit: number;
  liveIncidentCount: number;
  liveCritHighPercent: number;
  liveRejectionRate: number;
  livePressureSpikes: number;
}

// ── Analytics / Diagnostics ──────────────────────────────────────────────────

export interface SurvivalCurvePoint {
  t: number;
  survival: number | null;
}

export interface SurvivalCurveData {
  fleet_median_days: number;
  high_risk_median_days: number;
  fleet_closure_rate: number;
  high_risk_closure_rate: number;
  ratio: number | null;
  quotable: string;
  note?: string;
  n_fleet: number;
  n_high_risk: number;
  curves: {
    fleet: SurvivalCurvePoint[];
    high_risk: SurvivalCurvePoint[];
  };
}

export interface ControlChartReading {
  timestamp: string;
  pressure: number;
  ewma: number;
  ucl: number;
  lcl: number;
  drift_flag: boolean;
  spike: boolean;
}

export interface DriftEvent {
  spike_timestamp: string;
  spike_pressure: number;
  days_before_spike: number;
  drift_flag_at: string | null;
}

export interface SiteControlChart {
  site_id: string;
  grand_mean: number;
  ucl: number;
  lcl: number;
  n_readings: number;
  n_drift_flags: number;
  n_spikes: number;
  lead_time_days: number;
  readings: ControlChartReading[];
  drift_events: DriftEvent[];
}

export interface ControlChartData {
  fleet_avg_lead_time_days: number;
  quotable: string;
  ewma_lambda: number;
  ewma_L: number;
  sites: Record<string, SiteControlChart>;
}

export interface CorrelationScatterPoint {
  site_id: string;
  site_name: string;
  rejection_rate_30d: number;
  incident_count_30d: number;
  band: string;
}

export interface CorrelationData {
  pearson_r: number;
  p_value: number;
  n_sites: number;
  interpretation: string;
  quotable: string;
  scatter_points: CorrelationScatterPoint[];
}

export interface FeatureImportanceItem {
  name: string;
  importance: number;
  direction: "positive" | "negative";
  coefficient: number;
}

export interface FeatureImportanceData {
  model_version: string;
  label_definition: string;
  features: FeatureImportanceItem[];
}

export interface PredictionDto {
  siteId: string;
  asOfDate: string;
  probability: number;
  riskBand: string;
  modelVersion: string;
  topFeatures: string | null;
}
