-- V11: Add narrative column to the alerts table.
-- narrative stores a rich, human-readable sentence(s) generated by NarrativeService
-- at alert-creation time — ready to surface directly in the dashboard without recomputation.
-- TEXT allows multi-sentence paragraphs; NULL for any historic alerts created before V11.

ALTER TABLE alerts ADD COLUMN narrative TEXT;
